server:
  port: 8770

eureka:
  client:
    service-url:
      defaultZone: http://admin:mosh123456@localhost:8760/eureka/
  instance:
    #每10s向服务端发送一次心跳
    lease-renewal-interval-in-seconds: 10
    #通知服务端，如果60秒没有发送心跳，将我提出掉
    lease-expiration-duration-in-seconds: 60
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      
freemarker:
  settings:
    classic_compatible: true   #解决模板空指针问题

spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      notify:
        mail:
          enabled: false
      monitor:
        read-timeout: 20000
      ui:
        title: 服务监控中心
    mail:
      host: smtp.example.com
      username: wldd1116@163.com
      password: wym07240821
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true